version: "3.7"

services:
  mqtt:
    image: eclipse-mosquitto
    hostname: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "8000:8000"
      - "9001:9001"
    volumes:
      - ./.docker/mosquitto.conf:/mosquitto/config/mosquitto.conf
